a = input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type(a)}')
print(f'Só tem espaços? {a.isspace()}')
print(f'É maiúsculo? {a.isupper()}')
print(f'É minúsculo? {a.islower()}')
print(f'É capitalizado? {a.istitle()}')
print(f'É letra? {a.isalpha()}')
print(f'É alfanúmerico? {a.isalnum()}')
print(f'É um número? {a.isnumeric()}')
